name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Print Rust version
      run:  rustc -vV
    - name: Install example dependencies
      run:  sudo apt-get update && sudo apt-get -y install libsdl2-dev
    - name: Run tests
      run: cargo test --all-features --verbose
    - name: Run bench
      run: cargo bench --all-features --verbose
    - name: Run doc
      run: cargo doc --all-features --verbose
