---
name: Build
on: [push, pull_request]

jobs:
    cargo-toml-features:
        name: Generate Feature Combinations
        runs-on: ubuntu-latest
        outputs:
            feature-combinations: ${{ steps.cargo-toml-features.outputs.feature-combinations }}
        steps:
            - name: Check out repository
              uses: actions/checkout@v5
            - name: Determine Cargo Features
              id: cargo-toml-features
              uses: Holzhaus/cargo-toml-features-action@3afa751aae4071b2d1ca1c5fa42528a351c995f4

    build:
        needs: cargo-toml-features
        runs-on: ubuntu-latest
        strategy:
            matrix:
                features: ${{ fromJson(needs.cargo-toml-features.outputs.feature-combinations) }}
        steps:
            - name: Check out repository
              uses: actions/checkout@v5
            - name: Print Rust version
              run: rustc -vV
            - name: Install SDL2
              run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libsdl2-dev
            - name: Run tests
              run: cargo test --no-default-features --features "${{ join(matrix.features, ',') }}" --verbose
            - name: Run bench
              run: cargo bench --no-default-features --features "${{ join(matrix.features, ',') }}" --verbose
            - name: Run doc
              run: cargo doc --no-default-features --features "${{ join(matrix.features, ',') }}" --verbose
